/****************************************************************************
** Form interface generated from reading ui file 'AdSecControl_gui.ui'
**
** Created by: The User Interface Compiler ($Id: qt/main.cpp   3.3.6   edited Aug 31 2005 $)
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#ifndef ADSECCONTROLGUI_H
#define ADSECCONTROLGUI_H

#include <qvariant.h>
#include <qmainwindow.h>

class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QSpacerItem;
class QAction;
class QActionGroup;
class QToolBar;
class QPopupMenu;
class QButtonGroup;
class QPushButton;
class QLabel;
class QLCDNumber;
class QGroupBox;
class QProgressBar;
class QTabWidget;
class QWidget;
class KURLRequester;
class QCheckBox;
class QLineEdit;
class QComboBox;
class QTextEdit;

class AdSecControlGui : public QMainWindow
{
    Q_OBJECT

public:
    AdSecControlGui( QWidget* parent = 0, const char* name = 0, WFlags fl = WType_TopLevel );
    ~AdSecControlGui();

    QButtonGroup* commandButtonsGroup;
    QPushButton* onButton;
    QPushButton* offButton;
    QPushButton* loadProgramButton;
    QPushButton* calibrateButton;
    QPushButton* setFlatAoButton;
    QPushButton* restButton;
    QPushButton* aoToSl;
    QPushButton* slToAoButton;
    QPushButton* runAoButton;
    QPushButton* pauseAoButton;
    QPushButton* resumeAoButton;
    QPushButton* stopAoButton;
    QPushButton* recoverFailButton;
    QLabel* textLabel1_2;
    QPushButton* setFlatChopButton;
    QPushButton* setFlatSlButton;
    QPushButton* resetChopButton;
    QPushButton* resetSlButton;
    QPushButton* chopToSlButton;
    QPushButton* slToChopButton;
    QPushButton* chopToAoButton;
    QPushButton* aoToChopButton;
    QPushButton* runChopButton;
    QPushButton* stopChopButton;
    QPushButton* resetButton;
    QPushButton* resetAoButton;
    QLabel* textLabel2_2;
    QLabel* textLabel2_2_2;
    QLabel* textLabel2_2_2_2;
    QLabel* labModeLabel;
    QLabel* adSecArbitratorStatusLabel;
    QLabel* focalStationLabel;
    QLabel* lastCommandLabel;
    QLabel* lastCommandResultLabel;
    QLabel* textLabel1_3;
    QLCDNumber* WindSpeedLCD;
    QLabel* textLabel1_3_2;
    QLCDNumber* ElevationLCD;
    QLabel* labelCheckDew;
    QLCDNumber* SwaLCD;
    QGroupBox* groupBox4;
    QLabel* ShellRipStatus;
    QPushButton* forceRip;
    QLabel* TssStatus;
    QPushButton* ForceTssOn;
    QLabel* PowerStatus;
    QPushButton* ForcePowerOff;
    QLabel* labelSkipStatus;
    QProgressBar* progressBarSkip;
    QTabWidget* shapeTab;
    QWidget* tab;
    QButtonGroup* buttonGroup9;
    QLabel* textLabel10;
    QLabel* textLabel5;
    QLabel* textLabel6;
    QLabel* textLabel4_2_2;
    QLabel* curShape;
    KURLRequester* kURLshapeLoad;
    QPushButton* shapeLoad;
    KURLRequester* kURLshapeSave;
    QPushButton* shapeSaveButton;
    KURLRequester* kURLcommandVector;
    QPushButton* commandApplyVector;
    QCheckBox* checkBoxDefault;
    QButtonGroup* buttonGroup7;
    QLabel* textLabel1_4_2;
    QLabel* textLabel1_4;
    QLabel* textLabel1_4_3;
    QLabel* labelOffloadStatus;
    QLabel* labelHOOffloadStatus;
    QLabel* labelAccStatus;
    QPushButton* buttonOffloadEnable;
    QPushButton* buttonOffloadDisable;
    QPushButton* buttonHOOOffloadEnable;
    QPushButton* buttonHOOffloadDisable;
    QPushButton* buttonAccEnable;
    QPushButton* buttonAccDisable;
    QButtonGroup* buttonGroup7_2;
    QLabel* textLabel1_5;
    QLabel* textLabel1_6;
    QLabel* textLabel1_6_2;
    QLabel* z2label;
    QLabel* z2Total;
    QLabel* z2Applied;
    QLineEdit* z2Input;
    QLabel* z3label;
    QLabel* z3Total;
    QLabel* z3Applied;
    QLineEdit* z3Input;
    QLabel* z5label;
    QLabel* z5Total;
    QLabel* z5Applied;
    QLineEdit* z5Input;
    QLabel* z6label;
    QLabel* z6Total;
    QLabel* z6Applied;
    QLineEdit* z6Input;
    QLabel* z7label;
    QLabel* z7Total;
    QLabel* z7Applied;
    QLineEdit* z7Input;
    QLabel* z8label;
    QLabel* z8Total;
    QLabel* z8Applied;
    QLineEdit* z8Input;
    QLabel* z9label;
    QLabel* z9Total;
    QLabel* z9Applied;
    QLineEdit* z9Input;
    QPushButton* zernApply;
    QWidget* tab_2;
    QGroupBox* groupBox5;
    QLabel* textLabel1;
    QLabel* textLabel2;
    QLabel* textLabel3;
    QLabel* curModalBasis;
    QLabel* curRecMatrix;
    QLabel* curFiltering;
    QComboBox* comboModalBasis;
    KURLRequester* kURLrecMatrix;
    QComboBox* comboFiltering;
    QPushButton* buttonApply;
    QButtonGroup* buttonGroup6;
    QComboBox* comboKalman;
    QPushButton* buttonKalmanApply;
    QButtonGroup* buttonGroup4;
    QLabel* textLabel4_2;
    QLabel* textLabel5_2;
    QLabel* curGainVector;
    KURLRequester* kURLgainVector;
    QPushButton* gainApplyButton;
    QPushButton* buttonGainZero;
    QPushButton* buttonGain10modes;
    QLabel* textLabel1_7;
    QPushButton* buttonGainTTUp;
    QPushButton* buttonGainTTDown;
    QLabel* labelHO1;
    QPushButton* buttonGainHO1Up;
    QPushButton* buttonGainHO1Down;
    QLabel* labelHO2;
    QPushButton* buttonGainHO2Up;
    QPushButton* buttonGainHO2Down;
    QButtonGroup* buttonGroup3_2;
    QLabel* textLabel7_2;
    QLabel* textLabel7_2_2;
    QLabel* curDisturb;
    KURLRequester* kURLdisturbSelect;
    QPushButton* buttonDisturbSend;
    QWidget* TabPage;
    QButtonGroup* buttonGroupFS;
    QComboBox* comboFocalStations;
    QPushButton* buttonSetFocalStation;
    QWidget* TabPage_2;
    QTextEdit* processDumpText;
    QGroupBox* alertsBox;
    QTextEdit* alertsText;
    QLabel* messageLabel;
    QProgressBar* commandProgressBar;

public slots:
    virtual void forceDisable_clicked();
    virtual void ForceTssOn_toggled( bool);
    virtual void ForcePowerOff_clicked();
    virtual void buttonOffloadOff_clicked();
    virtual void buttonOffloadOn_clicked();
    virtual void buttonRecoverSkipFrame_clicked();
    virtual void gainApplyButton_clicked();
    virtual void buttonDisturbSend_clicked();
    virtual void buttonKalmanApply_clicked();
    virtual void buttonApply_clicked();
    virtual void commandApplyVector_clicked();
    virtual void shapeSaveButton_clicked();
    virtual void shapeLoad_clicked();
    virtual void onButton_clicked();
    virtual void offButton_clicked();
    virtual void loadProgramButton_clicked();
    virtual void calibrateButton_clicked();
    virtual void resetButton_clicked();
    virtual void setFlatAoButton_clicked();
    virtual void restButton_clicked();
    virtual void resetAoButton_clicked();
    virtual void aoToSl_clicked();
    virtual void slToAoButton_clicked();
    virtual void runAoButton_clicked();
    virtual void pauseAoButton_clicked();
    virtual void resumeAoButton_clicked();
    virtual void stopAoButton_clicked();
    virtual void recoverFailButton_clicked();
    virtual void setFlatChopButton_clicked();
    virtual void setFlatSlButton_clicked();
    virtual void resetChopButton_clicked();
    virtual void resetSlButton_clicked();
    virtual void chopToSlButton_released();
    virtual void slToChopButton_released();
    virtual void chopToAoButton_released();
    virtual void aoToChopButton_clicked();
    virtual void runChopButton_clicked();
    virtual void stopChopButton_clicked();
    virtual void forceRip_clicked();
    virtual void buttonHOOOffloadOn_clicked();
    virtual void buttonHOOffloadOff_clicked();
    virtual void buttonAccOn_clicked();
    virtual void buttonAccOff_clicked();
    virtual void chopToAoButton_clicked();
    virtual void slToChopButton_clicked();
    virtual void chopToSlButton_clicked();
    virtual void zernApply_clicked();
    virtual void z2_returnPressed();
    virtual void z3_returnPressed();
    virtual void z5_returnPressed();
    virtual void z6_returnPressed();
    virtual void z7_returnPressed();
    virtual void lineEdit1_5_textChanged( const QString & );
    virtual void z8_textChanged( const QString & );
    virtual void z9_returnPressed();
    virtual void z2Input_returnPressed();
    virtual void z3Input_returnPressed();
    virtual void z5Input_returnPressed();
    virtual void z6Input_returnPressed();
    virtual void z8Input_returnPressed();
    virtual void z9Input_returnPressed();
    virtual void z7Input_returnPressed();
    virtual void kURLshapeSave_openFileDialog( KURLRequester * );
    virtual void kURLshapeLoad_openFileDialog( KURLRequester * );
    virtual void kURLcommandVector_openFileDialog( KURLRequester * );
    virtual void radiofsNONE_clicked();
    virtual void buttonGroupFS_clicked( int );
    virtual void kURLrecMatrix_openFileDialog( KURLRequester * );
    virtual void kURLgainVector_openFileDialog( KURLRequester * );
    virtual void kURLdisturbSelect_openFileDialog( KURLRequester * );
    virtual void buttonGainZero_clicked();
    virtual void buttonGainHODown_clicked();
    virtual void buttonGainHOUp_clicked();
    virtual void buttonGainTTDown_clicked();
    virtual void buttonGainTTUp_clicked();
    virtual void pushSetFocalStation_clicked();
    virtual void buttonSetFocalStation_clicked();
    virtual void buttonOffloadEnable_clicked();
    virtual void buttonOffloadDisable_clicked();
    virtual void buttonHOOOffloadEnable_clicked();
    virtual void buttonHOOffloadDisable_clicked();
    virtual void buttonAccEnable_clicked();
    virtual void buttonAccDisable_clicked();
    virtual void comboModalBasis_activated( const QString & );
    virtual void buttonGainHO1Down_clicked();
    virtual void buttonGainHO1Up_clicked();
    virtual void buttonGainHO2Down_clicked();
    virtual void buttonGainHO2Up_clicked();
    virtual void buttonGain10modes_clicked();

protected:
    QHBoxLayout* AdSecControlGuiLayout;
    QVBoxLayout* layout56;
    QVBoxLayout* layout55;
    QHBoxLayout* layout54;
    QVBoxLayout* layout17;
    QVBoxLayout* layout53;
    QHBoxLayout* layout52;
    QHBoxLayout* layout48;
    QHBoxLayout* layout16;
    QHBoxLayout* layout36;
    QHBoxLayout* layout64;
    QHBoxLayout* layout62;
    QHBoxLayout* layout62_2;
    QHBoxLayout* groupBox4Layout;
    QVBoxLayout* layout54_2;
    QVBoxLayout* layout55_2;
    QVBoxLayout* layout56_2;
    QVBoxLayout* layout53_2;
    QVBoxLayout* tabLayout;
    QHBoxLayout* buttonGroup9Layout;
    QVBoxLayout* layout41;
    QVBoxLayout* layout59;
    QHBoxLayout* layout58;
    QHBoxLayout* layout57;
    QHBoxLayout* layout56_3;
    QVBoxLayout* layout47;
    QSpacerItem* spacer3;
    QSpacerItem* spacer2;
    QSpacerItem* spacer5;
    QHBoxLayout* layout46;
    QVBoxLayout* layout44;
    QVBoxLayout* layout40;
    QVBoxLayout* layout45;
    QHBoxLayout* layout41_2;
    QHBoxLayout* layout42;
    QHBoxLayout* layout43;
    QHBoxLayout* buttonGroup7_2Layout;
    QVBoxLayout* layout53_3;
    QSpacerItem* spacer7;
    QVBoxLayout* layout54_3;
    QVBoxLayout* layout55_3;
    QVBoxLayout* layout56_4;
    QVBoxLayout* layout57_2;
    QVBoxLayout* layout58_2;
    QVBoxLayout* layout59_2;
    QVBoxLayout* layout60;
    QVBoxLayout* tabLayout_2;
    QVBoxLayout* groupBox5Layout;
    QHBoxLayout* layout84;
    QVBoxLayout* layout22_2;
    QVBoxLayout* layout23_2;
    QVBoxLayout* layout23_3;
    QVBoxLayout* buttonGroup6Layout;
    QHBoxLayout* layout62_3;
    QVBoxLayout* buttonGroup4Layout;
    QHBoxLayout* layout48_2;
    QVBoxLayout* layout30;
    QVBoxLayout* layout25;
    QHBoxLayout* layout24;
    QHBoxLayout* layout54_4;
    QSpacerItem* spacer8;
    QSpacerItem* spacer8_2;
    QSpacerItem* spacer10;
    QSpacerItem* spacer9;
    QHBoxLayout* buttonGroup3_2Layout;
    QVBoxLayout* layout33;
    QVBoxLayout* layout24_3;
    QHBoxLayout* layout23;
    QHBoxLayout* layout22;
    QHBoxLayout* TabPageLayout;
    QVBoxLayout* alertsBoxLayout;
    QVBoxLayout* layout52_2;
    QHBoxLayout* layout51;

protected slots:
    virtual void languageChange();

};

#endif // ADSECCONTROLGUI_H
