/*
 * This class implements the AdSec Arbitrator FSM
 *
 * The core FSM is generated by FSMC based on
 * AdSecFsmCore.fsm
 *
 */

#ifndef ADSECFSM_H_INCLUDE
#define ADSECFSM_H_INCLUDE

#include "framework/AbstractFsm.h"
#include "AdSecCommandImplFactory.h"
#include "AdSecFsmCore.h"

#include "arblib/base/BasicOpCodes.h"
#include "arblib/adSecArb/AdSecOpCodes.h"

using namespace Arcetri::Arbitrator;

namespace Arcetri {
namespace AdSec_Arbitrator {

class AdSecFsm: public AbstractFsm, public AdSecFsmCore {

	public: // METHODS

		//  Constructor
    AdSecFsm(unsigned int commandHistoryMaxSize, string ident);

   		//  Destructor
   		virtual ~AdSecFsm(){};
                bool processCommand() const;

		virtual string currentStateAsString();

	private:
		/*
		 * Implement pure virtual base class methods.
		 */
		void trigger(OpCode code);
		void forceFailure();
		void forcePanic();

   public:
		void forceRest();

// The following map supports the conversion between OpCodes and Events
        private:
                map<OpCode,Event> EvtTable;

};

}
}

#endif // ADSECFSM_H_INCLUDE
