# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILEAOSLIB
MAKEFILEAOSLIB=.

AOSLIB_COMPILE = $(call test_uptodate,$(ADOPT_LIB)/aoslib,all,do_aoslib)

do_aoslib:
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB)/aoslib all

AOSLIB_LNK = $(ADOPT_SOURCE)/lib/aoslib/aoslib.a

endif
