# This file can be used by client applications to link
# this library: before using "XXX_LNK" please call the
# "xxx_compile" target.

ifndef MAKEFILEBASE
MAKEFILEBASE=.

BASE_COMPILE = $(call test_uptodate,$(ADOPT_LIB)/base,all,do_base_compile)

do_base_compile:
	@echo		
	$(Q)$(MAKE) $(MAKEOPTS) -C $(ADOPT_LIB)/base all

MSGLIB_LNK = $(MSGLIB_A) -lrt
THRDLIB_LNK = $(THRDLIB_A) -lpthread -lrt

endif
